### ISSUE TITLE
Tracker for potential small additions

### ISSUE THREAD

**Issue by usaoc** [racket/rhombus#435]
This is an issue specifically for tracking relatively *small* additions, such as convenience functions, forms, etc.  If you feel that a certain nicety is currently missing in Rhombus, please raise it; if you feel like implementing one of them, go ahead!  If you have a proposal for more systematic change, though, open a separate issue so that it’s easier to track it.

The current list:

- Reducer
  + [ ] Equivalents for `for/first`, `for/last`, etc.
  + [ ] Right fold, i.e., `for/foldr`
- Sequence
  + [x] Range with a decreasing step (or any step at all), cf. `in-range` (implemented, as `Range.step_by`)
    - A way for specifying a decresing step is still missing
- Function
  + [x] Canonical way to do function composition?  Say, operators like `<<`/`>>` (implemented, as `compose` and `compose_values`)
  + [x] Pipeline operator (`|>`)
    - Note: A simple version can be found in [`rhombus-compat`](https://github.com/samdphillips/rhombus-examples/blob/main/rhombus-compat/compat/function.rhm)
  + [ ] More pipeline operators
    - [x] `&>` for chaining `maybe` results? (implemented, as `?>`)
    - [ ] `!>` for chaining imperative functions?
  + [x] Anonymous function in the style of `fancy-app`?
    - Note: Previously discussed at #203
- Annotation
  + [x] `satisfying`, like `converting`, but for predicate annotations
- Srcloc
  + [ ] Use keyword arguments for constructor
- Exn
  + [ ] Use keyword arguments for constructor

**Comment by usaoc** [comment]
Closing as I never got to use this issue as much as I could.  Let’s try to open separate issues if any items are still worth looking into.
